package server

import (
	"fmt"
	"strings"
	"time"

	"github.com/sergmudrea/Black-Swarm/internal/protocol"
)

// ReportGenerator creates Markdown operational reports.
type ReportGenerator struct {
	findingStore FindingStore
	scheduler    TaskScheduler
	targets      TargetManager
}

// NewReportGenerator creates a new ReportGenerator.
func NewReportGenerator(fs FindingStore, s TaskScheduler, t TargetManager) *ReportGenerator {
	return &ReportGenerator{
		findingStore: fs,
		scheduler:    s,
		targets:      t,
	}
}

// Generate produces a full Markdown report of the current operation.
func (r *ReportGenerator) Generate() (string, error) {
	var b strings.Builder

	b.WriteString("# Siege Operation Report\n")
	b.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().UTC().Format(time.RFC3339)))

	// Targets
	b.WriteString("## Targets\n\n")
	if r.targets != nil {
		targets := r.targets.List()
		if len(targets) == 0 {
			b.WriteString("*No targets configured.*\n\n")
		} else {
			for _, t := range targets {
				b.WriteString(fmt.Sprintf("- %s\n", t))
			}
			b.WriteString("\n")
		}
	}

	// Tasks
	b.WriteString("## Tasks\n\n")
	if r.scheduler != nil {
		tasks := r.scheduler.PendingTasks()
		if len(tasks) == 0 {
			b.WriteString("*No pending tasks.*\n\n")
		} else {
			b.WriteString("| Task ID | Targets | Modules | Priority |\n")
			b.WriteString("|---------|---------|---------|----------|\n")
			for _, t := range tasks {
				modules := strings.Join(t.Modules, ", ")
				targets := strings.Join(t.Targets, ", ")
				b.WriteString(fmt.Sprintf("| %s | %s | %s | %d |\n",
					t.TaskID, targets, modules, t.Priority))
			}
			b.WriteString("\n")
		}
	}

	// Findings
	b.WriteString("## Findings\n\n")
	if r.findingStore != nil {
		stats, err := r.findingStore.Stats()
		if err == nil {
			if total, ok := stats["total"].(int); ok && total > 0 {
				b.WriteString(fmt.Sprintf("**Total findings:** %d\n\n", total))
				if bySev, ok := stats["by_severity"].(map[string]int); ok {
					b.WriteString("### By Severity\n\n")
					b.WriteString("| Severity | Count |\n")
					b.WriteString("|----------|-------|\n")
					for _, sev := range []string{"critical", "high", "medium", "low", "info"} {
						if count, exists := bySev[sev]; exists {
							b.WriteString(fmt.Sprintf("| %s | %d |\n", sev, count))
						}
					}
					b.WriteString("\n")
				}

				findings, _ := r.findingStore.Query("", "", "", 50, 0)
				if len(findings) > 0 {
					b.WriteString("### Recent Findings\n\n")
					b.WriteString("| Target | Title | Severity |\n")
					b.WriteString("|--------|-------|----------|\n")
					for _, f := range findings {
						title := f.Title
						if len(title) > 60 {
							title = title[:57] + "..."
						}
						b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
							f.Target, title, f.Severity))
					}
					b.WriteString("\n")
				}
			} else {
				b.WriteString("*No findings yet.*\n\n")
			}
		}
	}

	b.WriteString("---\n")
	b.WriteString("*Report generated by Siege (Black Swarm 3.0)*\n")
	return b.String(), nil
}
